"""Render the full construction for one problem to markdown: the FINAL prompt sent to
the model (best variant = worked-example hint + expert system prompt), the model's
actual OUTPUT, the judge verdict + feedback, and the SDPO teacher reprompt.

Serve base gemma on :8000 first, then:
  PYTHONPATH=src python src/render_example.py --pid 2608 --out reports/iteration-02/sample_construction.md
"""
import argparse

from openai import OpenAI

import sdpo_ojbench as S
import sdpo_prompts as P
from prompt_opt import EXPERT_SYS


def fence(s, lang=""):
    # 4-backtick outer fence so content containing ```python ... ``` renders correctly.
    return f"````{lang}\n{s}\n````"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pid", type=int, default=2608)
    ap.add_argument("--fail-pid", type=int, default=2416, help="a harder problem, to show the feedback path")
    ap.add_argument("--model", default="google/gemma-4-E2B-it")
    ap.add_argument("--n", type=int, default=6)
    ap.add_argument("--temperature", type=float, default=0.6)
    ap.add_argument("--max-tokens", type=int, default=8192)
    ap.add_argument("--base-url", default="http://localhost:8000/v1")
    ap.add_argument("--out", default="reports/iteration-02/sample_construction.md")
    args = ap.parse_args()
    pid = args.pid

    base_prompt = S.PROMPT_BY_ID[pid]
    user = S.augment_prompt_with_example(base_prompt, pid)   # worked-example hint
    system = EXPERT_SYS
    messages = [{"role": "system", "content": system}, {"role": "user", "content": user}]

    client = OpenAI(base_url=args.base_url, api_key="EMPTY", timeout=1800)
    resp = client.chat.completions.create(model=args.model, messages=messages,
                                          temperature=args.temperature, max_tokens=args.max_tokens, n=args.n)
    judged = []
    for ch in resp.choices:
        text = ch.message.content or ""
        reward, verdict, feedback = S.judge_completion(text, pid, which="private", language="python")
        judged.append((verdict, reward, text, feedback))
    ac = next((j for j in judged if j[0] == "AC"), None)
    fail = next((j for j in judged if j[0] != "AC"), None)

    md = []
    md.append(f"# Sample construction — loj-{pid} ({S.DIFF_BY_ID[pid]}, python)\n")
    md.append("Auto-generated by `src/render_example.py` (base `gemma-4-E2B-it`, best prompt variant = "
              "**worked-example hint + expert system prompt**). Shows the *final* prompt sent to the model, "
              "the model's *actual* output, the judge result, and the SDPO teacher reprompt.\n")
    md.append(f"Generated {len(judged)} samples (temp {args.temperature}); "
              f"verdicts: {', '.join(v for v, *_ in judged)}.\n")

    md.append("\n## 1. Final prompt sent to the model\n")
    md.append("**System message:**\n")
    md.append(fence(system))
    md.append("\n**User message** (task prompt with the worked-example hint injected into the empty "
              "`### Example` section):\n")
    md.append(fence(user))

    def block(title, j, user_prompt):
        v, r, text, fb = j
        md.append(f"\n## {title} — verdict `{v}`, reward `{r:.2f}`\n")
        md.append("**Model output:**\n")
        md.append(fence(text))
        md.append("\n**Judge feedback (the SDPO environment signal):**\n")
        md.append(fence(fb))
        md.append("\n**Teacher reprompt that SDPO would build from this rollout** "
                  f"({'copy-only: shows the AC solution' if v == 'AC' else 'feedback path: shows why it failed'}):\n")
        if v == "AC":
            tm = P.build_teacher_messages([{"role": "user", "content": user_prompt}], demo_text=text)
        else:
            tm = P.build_teacher_messages([{"role": "user", "content": user_prompt}], feedback_raw=fb)
        content = tm[-1]["content"] if isinstance(tm, list) else tm
        md.append(fence(content))

    if ac:
        block("2. A SOLVING rollout (AC)", ac, user)
    elif fail:
        block("2. A FAILING rollout", fail, user)

    # always show the feedback path on a harder problem (the iteration-02 mechanism)
    fp = args.fail_pid
    fuser = S.augment_prompt_with_example(S.PROMPT_BY_ID[fp], fp)
    fresp = client.chat.completions.create(
        model=args.model, messages=[{"role": "system", "content": system}, {"role": "user", "content": fuser}],
        temperature=args.temperature, max_tokens=args.max_tokens, n=3)
    ff = None
    for ch in fresp.choices:
        t = ch.message.content or ""
        rr, vv, fb = S.judge_completion(t, fp, which="private", language="python")
        if vv != "AC":
            ff = (vv, rr, t, fb)
            break
    if ff:
        md.append(f"\n---\n# Feedback path — loj-{fp} ({S.DIFF_BY_ID[fp]}, a harder problem)\n")
        block("3. A FAILING rollout (live judge feedback for the SDPO teacher)", ff, fuser)

    with open(args.out, "w") as f:
        f.write("\n".join(md) + "\n")
    print(f"wrote {args.out}  (AC={'yes' if ac else 'no'}, fail-example={'yes' if fail else 'no'})")


if __name__ == "__main__":
    main()
