"""Render EVERY prompt-construction scenario iteration 03 uses, to one reviewable
markdown file (the iteration-03 analogue of iteration-02's sample_construction.md).

Scenarios covered:
  1. Final prompt sent to the model — cp_method system prompt + task (worked-example
     hint injected when the Example section is empty).            [python]
  2. Language variant — the SAME problem's C++ task prompt.       [cpp]
  3. SUCCESS group -> SDPO teacher "copy" path: an AC rollout + the teacher reprompt
     (prompt + successful solution + "Correctly solve...").
  4. ALL-FAIL group -> SDPO teacher "feedback" path on a HARD problem: a WA rollout,
     its DENSE (fraction) reward + judge feedback, and the feedback teacher reprompt.
  5. Dense-reward signal gallery — the judge feedback text for WA / TLE / RE across the
     three hard archetypes (read from the saved diagnostic rollouts; no GPU needed).

Scenarios 1-4 need base served on :8000 (for the live AC). Scenario 5 reads
reports/iteration-03/data/hard_rollouts.json. Run:
  vllm serve google/gemma-4-E2B-it --port 8000 --dtype bfloat16 \
    --max-model-len 16384 --gpu-memory-utilization 0.85
  PYTHONPATH=src OJB_SPLITS=ojb_splits_full.json python src/render_scenarios.py \
    --out reports/iteration-03/prompt_scenarios.md
"""
import argparse
import json
import os

from openai import OpenAI

import sdpo_ojbench as S
import sdpo_prompts as P
from prompt_condition import CP_METHOD_SYS


def fence(s, lang=""):
    return f"````{lang}\n{s}\n````"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="google/gemma-4-E2B-it")
    ap.add_argument("--ac-pid", type=int, default=2608, help="easy problem that base reliably ACs (copy path)")
    ap.add_argument("--hard-pid", type=int, default=2442, help="reachable hard problem (feedback path)")
    ap.add_argument("--n", type=int, default=6)
    ap.add_argument("--temperature", type=float, default=0.7)
    ap.add_argument("--max-tokens", type=int, default=10240)
    ap.add_argument("--base-url", default="http://localhost:8000/v1")
    ap.add_argument("--rollouts", default="reports/iteration-03/data/hard_rollouts.json")
    ap.add_argument("--out", default="reports/iteration-03/prompt_scenarios.md")
    args = ap.parse_args()

    client = OpenAI(base_url=args.base_url, api_key="EMPTY", timeout=3600)
    sys_msg = CP_METHOD_SYS

    # ---- Scenario 1+3: easy problem, cp_method, get a genuine AC ----
    ac_pid = args.ac_pid
    ac_base = S.PROMPT_BY_ID[ac_pid]
    ac_user = S.augment_prompt_with_example(ac_base, ac_pid)  # hint if empty Example
    hint_fired = ac_user != ac_base
    resp = client.chat.completions.create(
        model=args.model, messages=[{"role": "system", "content": sys_msg}, {"role": "user", "content": ac_user}],
        temperature=args.temperature, max_tokens=args.max_tokens, n=args.n)
    ac_judged = []
    for ch in resp.choices:
        t = ch.message.content or ""
        r, v, fb = S.judge_completion(t, ac_pid, which="private", language="python", reward_mode="fraction")
        ac_judged.append((v, r, t, fb))
    ac = next((j for j in ac_judged if j[0] == "AC"), None) or max(ac_judged, key=lambda j: j[1])

    # ---- Scenario 4: hard problem, cp_method, a WA rollout w/ dense feedback ----
    hard_pid = args.hard_pid
    hard_user = S.PROMPT_BY_ID[hard_pid]
    hresp = client.chat.completions.create(
        model=args.model, messages=[{"role": "system", "content": sys_msg}, {"role": "user", "content": hard_user}],
        temperature=args.temperature, max_tokens=args.max_tokens, n=4)
    hjudged = []
    for ch in hresp.choices:
        t = ch.message.content or ""
        r, v, fb = S.judge_completion(t, hard_pid, which="private", language="python", reward_mode="fraction")
        hjudged.append((v, r, t, fb))
    hard = max(hjudged, key=lambda j: j[1])  # best partial-credit WA

    md = []
    md.append(f"# Iteration 03 — prompt scenarios (all constructions, reviewable)\n")
    md.append("Auto-generated by `src/render_scenarios.py` (base `gemma-4-E2B-it`). Shows the *exact* "
              "text the model sees in every scenario iteration-03 uses: the **cp_method** system prompt, "
              "the task prompt (+ worked-example hint), the **python/cpp** variants, the **dense (fraction) "
              "reward** judge feedback, and both **SDPO teacher** paths (copy + feedback).\n")
    md.append(f"Live samples: loj-{ac_pid} (easy) n={args.n}, verdicts "
              f"{', '.join(v for v, *_ in ac_judged)}; loj-{hard_pid} (hard) n=4, verdicts "
              f"{', '.join(v for v, *_ in hjudged)}.\n")

    # Scenario 1
    md.append("\n## 1. Final prompt sent to the model (cp_method system + task)\n")
    md.append("**System message** — the iteration-03 default (targets base's over-theorizing on hard: "
              "implement the *stated* rule, tier by the Data Range table, output code):\n")
    md.append(fence(sys_msg))
    md.append(f"\n**User message** — loj-{ac_pid} task prompt"
              + (" with the worked-example hint injected into the empty `### Example` section"
                 if hint_fired else " (Example section already populated; hint is a no-op)") + ":\n")
    md.append(fence(ac_user))

    # Scenario 2 — cpp variant
    md.append("\n## 2. Language variant — the same problem in C++\n")
    md.append("Each problem has a python *and* a cpp prompt; they are split-locked to the same side "
              "(no cross-language leak). Only the trailing **Format** block differs:\n")
    cpp_prompt = S.CPP_PROMPT_BY_ID[ac_pid]
    # show just the differing format tail to keep it short
    tail = cpp_prompt[-700:]
    md.append(fence("...\n" + tail, ))

    # Scenario 3 — copy path (AC)
    v, r, text, fb = ac
    md.append(f"\n## 3. SUCCESS group → SDPO teacher *copy* path — loj-{ac_pid}, verdict `{v}`, reward `{r:.2f}`\n")
    md.append("When a rollout in the group succeeds (reward ≥ threshold), SDPO distills it into the "
              "failing group-mates. The teacher reprompt = original prompt + the successful solution + a "
              "\"Correctly solve\" instruction.\n")
    md.append("**Model output (the successful rollout):**\n")
    md.append(fence(text))
    md.append("\n**Teacher reprompt SDPO builds (copy path):**\n")
    tm = P.build_teacher_messages([{"role": "user", "content": ac_user}], demo_text=text)
    md.append(fence(tm[-1]["content"] if isinstance(tm, list) else tm))

    # Scenario 4 — feedback path (hard, dense reward)
    v, r, text, fb = hard
    md.append(f"\n## 4. ALL-FAIL group → SDPO teacher *feedback* path — loj-{hard_pid} (hard), "
              f"verdict `{v}`, **dense reward `{r:.2f}`**\n")
    md.append("On hard groups where *no* rollout ACs (iteration-01's dead spot), there is no solution to "
              "copy — so the teacher is conditioned on the **live judge feedback** instead. The **dense "
              "(fraction) reward** also gives these all-fail groups non-zero advantage variance (the "
              "iteration-02 fix). Below: the failing rollout, the judge feedback that becomes the teacher "
              "signal, and the reprompt.\n")
    md.append("**Model output (failing rollout):**\n")
    md.append(fence(text))
    md.append("\n**Judge feedback (dense reward — the SDPO environment signal):**\n")
    md.append(fence(fb))
    md.append("\n**Teacher reprompt SDPO builds (feedback path):**\n")
    tm = P.build_teacher_messages([{"role": "user", "content": hard_user}], feedback_raw=fb)
    md.append(fence(tm[-1]["content"] if isinstance(tm, list) else tm))

    # Scenario 5 — dense-reward signal gallery from saved diagnostics
    md.append("\n## 5. Dense-reward signal gallery — what the teacher sees across hard archetypes\n")
    md.append("The judge feedback text varies by failure mode; dense reward distinguishes "
              "\"passes 14/20\" from \"0/20\". From the saved diagnostic rollouts "
              "(`data/hard_rollouts.json`):\n")
    if os.path.exists(args.rollouts):
        saved = json.load(open(args.rollouts))
        want = [("2442", "WA — right idea, wrong value"), ("2131", "TLE — too slow"),
                ("900011", "RE — crash / edge case")]
        for pid, label in want:
            rolls = saved.get(pid) or saved.get(int(pid)) if isinstance(saved, dict) else None
            if not rolls:
                continue
            # pick the rollout whose verdict matches the archetype label's prefix
            tag = label.split(" ")[0]
            pick = next((x for x in rolls if x["verdict"] == tag), rolls[0])
            md.append(f"\n**loj-{pid} — {label}** (reward `{pick['reward']:.2f}`):\n")
            md.append(fence(pick["feedback"]))
    else:
        md.append("_(run `src/diagnose_hard.py` first to populate the gallery)_\n")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    open(args.out, "w").write("\n".join(md) + "\n")
    print(f"wrote {args.out}  (AC={'yes' if ac[0]=='AC' else 'no, best '+format(ac[1],'.2f')}; "
          f"hard best {hard[1]:.2f})")


if __name__ == "__main__":
    main()
